const toolCapabilities = {
  figma_get_status: "runtime.status",
  figma_navigate: "runtime.status",
  figma_list_open_files: "runtime.status",
  figma_reconnect: "runtime.status",
  figma_execute: "runtime.execute",
  figma_clear_console: "logs.read",
  figma_watch_console: "logs.read",
  figma_reload_plugin: "runtime.status",
  figma_get_selection: "selection.read",
  figma_get_node: "node.read",
  figma_get_children: "node.read",
  figma_get_file_context: "runtime.status",
  figma_get_file_data: "node.read",
  figma_get_file_for_plugin: "node.read",
  figma_get_screenshot: "screenshots.capture",
  figma_get_styles: "styles.read",
  figma_get_variables: "variables.read",
  figma_get_components: "components.read",
  figma_get_component_property_catalog: "components.read",
  figma_get_bound_variables: "node.read",
  figma_create_node: "node.write",
  figma_delete_node: "node.write",
  figma_move_node: "node.write",
  figma_resize_node: "node.write",
  figma_rename_node: "node.write",
  figma_set_text: "node.write",
  figma_update_figjam_node: "node.write",
  figma_set_description: "node.write",
  figma_set_image_fill: "node.write",
  figma_set_fills: "node.write",
  figma_set_strokes: "node.write",
  figma_set_layout: "node.write",
  figma_bind_variable: "variables.write",
  figma_set_variable_mode: "variables.write",
  figma_apply_style: "node.write",
  figma_create_style: "styles.write",
  figma_delete_style: "styles.write",
  figma_cleanup_artifacts: "node.write",
  figma_clone_node: "node.write",
  figma_create_child: "node.write",
  figma_create_variable_collection: "variables.write",
  figma_add_mode: "variables.write",
  figma_rename_mode: "variables.write",
  figma_create_variable: "variables.write",
  figma_update_variable: "variables.write",
  figma_batch_update_variables: "variables.write",
  figma_delete_variable: "variables.write",
  figma_create_component: "components.write",
  figma_search_components: "components.read",
  figma_get_library_components: "components.read",
  figma_add_component_property: "components.write",
  figma_edit_component_property: "components.write",
  figma_delete_component_property: "components.write",
  figma_arrange_component_set: "components.write",
  figma_instantiate_component: "components.write",
  figma_set_instance_properties: "components.write",
  figma_get_operation_trace: "logs.read",
  figma_get_design_changes: "logs.read",
  figma_get_console_logs: "logs.read",
  figma_take_screenshot: "screenshots.capture"
} as const;

export function getRequiredCapability(toolName: string) {
  return toolCapabilities[toolName as keyof typeof toolCapabilities] || null;
}
