import { describe, expect, it } from "vitest";
import { toolRegistry } from "./index.js";

describe("tool registry", () => {
  it("exports the expected MCP surface groups", () => {
    const names = toolRegistry.map((tool) => tool.name);

    expect(names).toContain("figma_get_status");
    expect(names).toContain("figma_get_selection");
    expect(names).toContain("figma_get_bound_variables");
    expect(names).toContain("figma_get_file_data");
    expect(names).toContain("figma_create_node");
    expect(names).toContain("figma_set_layout");
    expect(names).toContain("figma_bind_variable");
    expect(names).toContain("figma_batch_bind_variables");
    expect(names).toContain("figma_set_variable_mode");
    expect(names).toContain("figma_get_styles");
    expect(names).toContain("figma_apply_style");
    expect(names).toContain("figma_batch_apply_styles");
    expect(names).toContain("figma_create_style");
    expect(names).toContain("figma_delete_style");
    expect(names).toContain("figma_create_variable_collection");
    expect(names).toContain("figma_batch_create_variables");
    expect(names).toContain("figma_rename_variable");
    expect(names).toContain("figma_delete_variable_collection");
    expect(names).toContain("figma_setup_design_tokens");
    expect(names).toContain("figma_create_component");
    expect(names).toContain("figma_get_component_details");
    expect(names).toContain("figma_get_component");
    expect(names).toContain("figma_get_component_property_catalog");
    expect(names).toContain("figma_get_component_family_health");
    expect(names).toContain("figma_get_component_image");
    expect(names).toContain("figma_add_component_property");
    expect(names).toContain("figma_edit_component_property");
    expect(names).toContain("figma_delete_component_property");
    expect(names).toContain("figma_batch_instantiate_components");
    expect(names).toContain("figma_batch_set_instance_properties");
    expect(names).toContain("figma_get_comments");
    expect(names).toContain("figma_get_inline_comments");
    expect(names).toContain("figma_get_comment_replies");
    expect(names).toContain("figma_get_comment_thread");
    expect(names).toContain("figma_get_node_comments");
    expect(names).toContain("figma_post_inline_comment");
    expect(names).toContain("figma_reply_to_comment");
    expect(names).toContain("figma_get_design_system_summary");
    expect(names).toContain("figma_get_dashboard");
    expect(names).toContain("figma_generate_change_impact_summary");
    expect(names).toContain("figma_get_release_readiness");
    expect(names).toContain("figma_get_release_readiness_trend");
    expect(names).toContain("figma_get_design_system_kit");
    expect(names).toContain("figma_browse_tokens");
    expect(names).toContain("figma_browse_design_system");
    expect(names).toContain("figma_get_token_values");
    expect(names).toContain("figma_generate_design_system_report");
    expect(names).toContain("figma_audit_design_system");
    expect(names).toContain("figma_get_audit_waivers");
    expect(names).toContain("figma_upsert_audit_waiver");
    expect(names).toContain("figma_delete_audit_waiver");
    expect(names).toContain("figma_get_component_for_development");
    expect(names).toContain("figma_check_design_parity");
    expect(names).toContain("figma_generate_component_doc");
    expect(names).toContain("figma_detect_doc_drift");
    expect(names).toContain("figma_post_comment");
    expect(names).toContain("figma_delete_comment");
    expect(names).toContain("figma_execute");
    expect(names).toContain("figma_clear_console");
    expect(names).toContain("figma_watch_console");
    expect(names).toContain("figma_reload_plugin");
    expect(names).toContain("figma_get_operation_trace");
    expect(names).toContain("figma_generate_verification_report");
    expect(names).toContain("figma_generate_section_report");
  });
});
