export function createComponentFactory({
  figma,
  DEFAULT_BLUE,
  hexToRgb,
  positionNearViewportCenter,
  parseName
}) {
  async function createComponentFromText(text) {
    const lower = text.toLowerCase();
    const name = parseName(text) || "Runtime Component";
    let variant = "generic";
    if (
      lower.includes("form") ||
      ((lower.includes("kullanıcı adı") || lower.includes("kullanici adi")) &&
        (lower.includes("şifre") || lower.includes("sifre") || lower.includes("password")))
    ) {
      variant = "login-form";
    } else if (
      lower.includes("hesap seçim") ||
      lower.includes("hesap secim") ||
      lower.includes("account selection") ||
      lower.includes("account picker")
    ) {
      variant = "account-selection";
    } else if (lower.includes("button") || lower.includes("buton")) {
      variant = "button";
    } else if (lower.includes("card") || lower.includes("kart")) {
      variant = "card";
    } else if (lower.includes("input")) {
      variant = "input";
    }

    const component = await createNamedComponent(variant, name);
    return {
      message: `${component.name} component'i oluşturuldu.`,
      data: { nodeId: component.id, variant }
    };
  }

  async function createNamedComponent(variant, name) {
    await figma.loadFontAsync({ family: "Inter", style: "Regular" });
    await figma.loadFontAsync({ family: "Inter", style: "Medium" });

    const component = figma.createComponent();
    component.name = name;

    if (variant === "button") {
      component.layoutMode = "HORIZONTAL";
      component.primaryAxisSizingMode = "AUTO";
      component.counterAxisSizingMode = "AUTO";
      component.paddingLeft = 16;
      component.paddingRight = 16;
      component.paddingTop = 10;
      component.paddingBottom = 10;
      component.cornerRadius = 10;
      component.fills = [{ type: "SOLID", color: hexToRgb(DEFAULT_BLUE) }];

      const label = figma.createText();
      label.characters = "Button";
      label.fontName = { family: "Inter", style: "Medium" };
      label.fontSize = 14;
      label.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      component.appendChild(label);
    } else if (variant === "card") {
      component.layoutMode = "VERTICAL";
      component.primaryAxisSizingMode = "AUTO";
      component.counterAxisSizingMode = "FIXED";
      component.resize(280, 1);
      component.itemSpacing = 8;
      component.paddingLeft = 16;
      component.paddingRight = 16;
      component.paddingTop = 16;
      component.paddingBottom = 16;
      component.cornerRadius = 12;
      component.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      component.strokes = [{ type: "SOLID", color: hexToRgb("#D6D6D6") }];
      component.strokeWeight = 1;

      const title = figma.createText();
      title.characters = "Card Title";
      title.fontName = { family: "Inter", style: "Medium" };
      title.fontSize = 16;
      title.fills = [{ type: "SOLID", color: hexToRgb("#111111") }];

      const body = figma.createText();
      body.characters = "Card body text generated by Figma Runtime MCP.";
      body.fontName = { family: "Inter", style: "Regular" };
      body.fontSize = 13;
      body.fills = [{ type: "SOLID", color: hexToRgb("#444444") }];

      component.appendChild(title);
      component.appendChild(body);
    } else if (variant === "input") {
      component.layoutMode = "HORIZONTAL";
      component.primaryAxisSizingMode = "FIXED";
      component.counterAxisSizingMode = "FIXED";
      component.resize(280, 40);
      component.paddingLeft = 12;
      component.paddingRight = 12;
      component.cornerRadius = 8;
      component.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      component.strokes = [{ type: "SOLID", color: hexToRgb("#CFCFCF") }];
      component.strokeWeight = 1;

      const placeholder = figma.createText();
      placeholder.characters = "Input";
      placeholder.fontName = { family: "Inter", style: "Regular" };
      placeholder.fontSize = 14;
      placeholder.fills = [{ type: "SOLID", color: hexToRgb("#7A7A7A") }];
      component.appendChild(placeholder);
    } else if (variant === "login-form") {
      component.layoutMode = "VERTICAL";
      component.primaryAxisSizingMode = "FIXED";
      component.counterAxisSizingMode = "AUTO";
      component.resize(320, 1);
      component.itemSpacing = 10;
      component.paddingLeft = 16;
      component.paddingRight = 16;
      component.paddingTop = 16;
      component.paddingBottom = 16;
      component.cornerRadius = 12;
      component.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      component.strokes = [{ type: "SOLID", color: hexToRgb("#D6D6D6") }];
      component.strokeWeight = 1;

      const title = figma.createText();
      title.characters = "Giriş";
      title.fontName = { family: "Inter", style: "Medium" };
      title.fontSize = 16;
      title.fills = [{ type: "SOLID", color: hexToRgb("#111111") }];

      const username = figma.createFrame();
      username.layoutMode = "HORIZONTAL";
      username.primaryAxisSizingMode = "FIXED";
      username.counterAxisSizingMode = "FIXED";
      username.resize(288, 40);
      username.paddingLeft = 12;
      username.paddingRight = 12;
      username.cornerRadius = 8;
      username.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      username.strokes = [{ type: "SOLID", color: hexToRgb("#CFCFCF") }];
      username.strokeWeight = 1;

      const usernameText = figma.createText();
      usernameText.characters = "Kullanıcı adı";
      usernameText.fontName = { family: "Inter", style: "Regular" };
      usernameText.fontSize = 14;
      usernameText.fills = [{ type: "SOLID", color: hexToRgb("#7A7A7A") }];
      username.appendChild(usernameText);

      const password = figma.createFrame();
      password.layoutMode = "HORIZONTAL";
      password.primaryAxisSizingMode = "FIXED";
      password.counterAxisSizingMode = "FIXED";
      password.resize(288, 40);
      password.paddingLeft = 12;
      password.paddingRight = 12;
      password.cornerRadius = 8;
      password.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      password.strokes = [{ type: "SOLID", color: hexToRgb("#CFCFCF") }];
      password.strokeWeight = 1;

      const passwordText = figma.createText();
      passwordText.characters = "Şifre";
      passwordText.fontName = { family: "Inter", style: "Regular" };
      passwordText.fontSize = 14;
      passwordText.fills = [{ type: "SOLID", color: hexToRgb("#7A7A7A") }];
      password.appendChild(passwordText);

      const submit = figma.createFrame();
      submit.layoutMode = "HORIZONTAL";
      submit.primaryAxisSizingMode = "FIXED";
      submit.counterAxisSizingMode = "FIXED";
      submit.resize(288, 40);
      submit.cornerRadius = 8;
      submit.fills = [{ type: "SOLID", color: hexToRgb("#007BFF") }];
      submit.primaryAxisAlignItems = "CENTER";
      submit.counterAxisAlignItems = "CENTER";

      const submitText = figma.createText();
      submitText.characters = "Giriş Yap";
      submitText.fontName = { family: "Inter", style: "Medium" };
      submitText.fontSize = 14;
      submitText.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      submit.appendChild(submitText);

      component.appendChild(title);
      component.appendChild(username);
      component.appendChild(password);
      component.appendChild(submit);
    } else if (variant === "account-selection") {
      component.layoutMode = "HORIZONTAL";
      component.primaryAxisSizingMode = "FIXED";
      component.counterAxisSizingMode = "AUTO";
      component.resize(360, 1);
      component.paddingLeft = 14;
      component.paddingRight = 14;
      component.paddingTop = 12;
      component.paddingBottom = 12;
      component.itemSpacing = 12;
      component.cornerRadius = 12;
      component.fills = [{ type: "SOLID", color: hexToRgb("#FFFFFF") }];
      component.strokes = [{ type: "SOLID", color: hexToRgb("#D9E2EC") }];
      component.strokeWeight = 1;

      const iconWrap = figma.createFrame();
      iconWrap.name = "Icon Area";
      iconWrap.layoutMode = "VERTICAL";
      iconWrap.primaryAxisSizingMode = "FIXED";
      iconWrap.counterAxisSizingMode = "FIXED";
      iconWrap.resize(40, 40);
      iconWrap.cornerRadius = 20;
      iconWrap.fills = [{ type: "SOLID", color: hexToRgb("#EEF5FF") }];
      iconWrap.strokes = [{ type: "SOLID", color: hexToRgb("#C8DDFE") }];
      iconWrap.strokeWeight = 1;
      iconWrap.primaryAxisAlignItems = "CENTER";
      iconWrap.counterAxisAlignItems = "CENTER";

      const iconGlyph = figma.createText();
      iconGlyph.characters = "H";
      iconGlyph.fontName = { family: "Inter", style: "Medium" };
      iconGlyph.fontSize = 16;
      iconGlyph.fills = [{ type: "SOLID", color: hexToRgb("#2C5CC5") }];
      iconWrap.appendChild(iconGlyph);

      const content = figma.createFrame();
      content.layoutMode = "VERTICAL";
      content.primaryAxisSizingMode = "AUTO";
      content.counterAxisSizingMode = "AUTO";
      content.itemSpacing = 4;
      content.fills = [];

      const title = figma.createText();
      title.characters = "Hesap Seçimi";
      title.fontName = { family: "Inter", style: "Medium" };
      title.fontSize = 14;
      title.fills = [{ type: "SOLID", color: hexToRgb("#111111") }];

      const subtitle = figma.createText();
      subtitle.characters = "İşlem yapmak istediğiniz hesabı seçin";
      subtitle.fontName = { family: "Inter", style: "Regular" };
      subtitle.fontSize = 12;
      subtitle.fills = [{ type: "SOLID", color: hexToRgb("#5B6670") }];

      content.appendChild(title);
      content.appendChild(subtitle);

      component.appendChild(iconWrap);
      component.appendChild(content);
    } else {
      component.layoutMode = "VERTICAL";
      component.primaryAxisSizingMode = "FIXED";
      component.counterAxisSizingMode = "FIXED";
      component.resize(240, 140);
      component.cornerRadius = 12;
      component.fills = [{ type: "SOLID", color: hexToRgb("#F3F6FA") }];
      component.strokes = [{ type: "SOLID", color: hexToRgb("#CAD5E2") }];
      component.strokeWeight = 1;

      const label = figma.createText();
      label.characters = "Custom Component";
      label.fontName = { family: "Inter", style: "Medium" };
      label.fontSize = 14;
      label.fills = [{ type: "SOLID", color: hexToRgb("#222222") }];
      label.x = 12;
      label.y = 12;
      component.appendChild(label);
    }

    positionNearViewportCenter(component);
    figma.currentPage.appendChild(component);
    figma.currentPage.selection = [component];
    figma.viewport.scrollAndZoomIntoView([component]);
    return component;
  }

  return {
    createComponentFromText,
    createNamedComponent
  };
}
